workflows:
  my-workflow:
    publishing:
      app_store_connect:
        api_key: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/1Md0bswgqrvPKvB37GHjOp0MnyQQNYSY8ELx1gPMROgCgYIKoZIzj0DAQehRANCAAT30ujJwL81SzBI7qLMIWKHKuwPQeCMxR0JIblZfAZmZ4mKIBD01SQDoBKheP7ikxW7BEyI2fC4jtTWlcoJJUjv
        key_id: GBA5Y8Y3LX
        issuer_id: 9bb14943-c02d-46b4-99a9-f088f800e133
        submit_to_testflight: true
        beta_groups:
          - Beta Testers
